### ISSUE TITLE
[Win]Test starts - Browser opens and stays idle

### ISSUE THREAD

**Issue by asharma88** [Frameworkium/frameworkium-examples#3]
Hello,

Platform: Windows 10
Code Base: Frameworkium-Examples

Steps to reproduce 
1.) mvn clean verify -Dbrowser=chrome -Dwebdriver.chrome.driver=c:\path\to\chromedriver.exe

Expected: Browser opens and navigates to SUT url
Actual: Browser opens and does nothing.

I re-ran the same on a macbook pro, everything runs as expected.

Thanks Arjun

**Comment by ham1** [comment]
Which version of Java, Chrome, Chrome Driver and maven are you using? Also could you include the relevant parts (maybe a stacktrace?) of the `frameworkium.log` file? Thanks.

**Comment by ham1** [comment]
Also which version of `frameworkium-core` do you have in the `pom.xml` file?

**Comment by asharma88** [comment]
Hi Graham,

Thank you for the prompt reply.

Google Chrome is up to date
Version 65.0.3325.181 (Official Build) (64-bit)

chrome driver -> 2.37

Firefox -> 59.0.2 (64-bit)
Gecko Driver -> v0.20.1

Framework-core -> <version>2.7.2</version>

Code base -> Frameworkium-Examples (unchanged) @ commit b6041e829194d33da70f8ee7c59eb819403e1221

**Comment by asharma88** [comment]
I tried again on another windows box, everything is working as expected. Must be an environment issue.

Closing. Apologies for the hassle.
